INSERT INTO USERS (USERNAME, PASSWORD, FULL_NAME, ROLE, STATUS)
VALUES ('admin', '123456', 'Quản trị viên', 'ADMIN', 'ACTIVE');

INSERT INTO USERS (USERNAME, PASSWORD, FULL_NAME, ROLE, STATUS)
VALUES ('staff1', '123456', 'Nhân viên 1', 'STAFF', 'ACTIVE');

INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE, DESCRIPTION, STATUS)
VALUES ('Sân 5A', '5', 'Sân 5 người khu A', 'ACTIVE');

INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE, DESCRIPTION, STATUS)
VALUES ('Sân 5B', '5', 'Sân 5 người khu B', 'ACTIVE');

INSERT INTO FIELDS (FIELD_NAME, FIELD_TYPE, DESCRIPTION, STATUS)
VALUES ('Sân 7A', '7', 'Sân 7 người khu A', 'ACTIVE');

INSERT INTO CUSTOMERS (FULL_NAME, PHONE, NOTE)
VALUES ('Nguyễn Văn A', '0901234567', 'Khách quen');

INSERT INTO CUSTOMERS (FULL_NAME, PHONE, NOTE)
VALUES ('Trần Văn B', '0912345678', 'Đặt buổi tối');

INSERT INTO PRICE_RULES (FIELD_TYPE, DAY_TYPE, START_MINUTE, END_MINUTE, PRICE_PER_HOUR, STATUS)
VALUES ('5', 'WEEKDAY', 360, 960, 200000, 'ACTIVE');

INSERT INTO PRICE_RULES (FIELD_TYPE, DAY_TYPE, START_MINUTE, END_MINUTE, PRICE_PER_HOUR, STATUS)
VALUES ('5', 'WEEKDAY', 960, 1320, 350000, 'ACTIVE');

INSERT INTO PRICE_RULES (FIELD_TYPE, DAY_TYPE, START_MINUTE, END_MINUTE, PRICE_PER_HOUR, STATUS)
VALUES ('7', 'WEEKDAY', 360, 960, 300000, 'ACTIVE');

INSERT INTO PRICE_RULES (FIELD_TYPE, DAY_TYPE, START_MINUTE, END_MINUTE, PRICE_PER_HOUR, STATUS)
VALUES ('7', 'WEEKDAY', 960, 1320, 500000, 'ACTIVE');
