CREATE TABLE vai_tro (
    ma_vai_tro       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_vai_tro      VARCHAR2(30) NOT NULL UNIQUE,
    mo_ta            VARCHAR2(100) NOT NULL
);

CREATE TABLE tai_khoan (
    ma_tai_khoan          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap         VARCHAR2(50) NOT NULL UNIQUE,
    mat_khau              VARCHAR2(255) NOT NULL,
    ho_ten                VARCHAR2(150) NOT NULL,
    email                 VARCHAR2(100) UNIQUE,
    so_dien_thoai         VARCHAR2(20) UNIQUE,
    ma_vai_tro            NUMBER NOT NULL,
    trang_thai_tai_khoan  VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    ngay_tao              DATE DEFAULT SYSDATE,
    ngay_cap_nhat         DATE DEFAULT SYSDATE,
    CONSTRAINT fk_tai_khoan_vai_tro FOREIGN KEY (ma_vai_tro) REFERENCES vai_tro(ma_vai_tro),
    CONSTRAINT chk_trang_thai_tai_khoan 
        CHECK (trang_thai_tai_khoan IN ('HOAT_DONG', 'BI_KHOA', 'NGUNG_HOAT_DONG'))
);

-- =========================
-- 4. BANG NHAN VIEN
-- =========================
CREATE TABLE nhan_vien (
    ma_nhan_vien           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_tai_khoan           NUMBER NOT NULL UNIQUE,
    ma_nhan_vien_code      VARCHAR2(30) NOT NULL UNIQUE,
    ngay_vao_lam           DATE DEFAULT SYSDATE,
    trang_thai_nhan_vien   VARCHAR2(20) DEFAULT 'DANG_LAM_VIEC' NOT NULL,
    ghi_chu                VARCHAR2(500),
    CONSTRAINT fk_nhan_vien_tai_khoan FOREIGN KEY (ma_tai_khoan) REFERENCES tai_khoan(ma_tai_khoan),
    CONSTRAINT chk_trang_thai_nhan_vien 
        CHECK (trang_thai_nhan_vien IN ('DANG_LAM_VIEC', 'DA_NGHI'))
);

-- =========================
-- 5. BANG KHACH HANG
-- =========================
CREATE TABLE khach_hang (
    ma_khach_hang             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_tai_khoan              NUMBER UNIQUE,
    ma_khach_hang_code        VARCHAR2(30) NOT NULL UNIQUE,
    ngay_sinh                 DATE,
    gioi_tinh                 VARCHAR2(10),
    dia_chi                   VARCHAR2(255),
    trang_thai_khach_hang     VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    ngay_tao                  DATE DEFAULT SYSDATE,
    CONSTRAINT fk_khach_hang_tai_khoan FOREIGN KEY (ma_tai_khoan) REFERENCES tai_khoan(ma_tai_khoan),
    CONSTRAINT chk_gioi_tinh 
        CHECK (gioi_tinh IN ('NAM', 'NU', 'KHAC')),
    CONSTRAINT chk_trang_thai_khach_hang 
        CHECK (trang_thai_khach_hang IN ('HOAT_DONG', 'NGUNG_HOAT_DONG'))
);

-- =========================
-- 6. BANG LOAI SAN
-- =========================
CREATE TABLE loai_san (
    ma_loai_san         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_loai_san        VARCHAR2(100) NOT NULL UNIQUE,
    mo_ta               VARCHAR2(255)
);

-- =========================
-- 7. BANG SAN BONG
-- =========================
CREATE TABLE san_bong (
    ma_san              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_san_code         VARCHAR2(30) NOT NULL UNIQUE,
    ten_san             VARCHAR2(100) NOT NULL,
    ma_loai_san         NUMBER NOT NULL,
    vi_tri              VARCHAR2(255),
    suc_chua            NUMBER,
    trang_thai_san      VARCHAR2(20) DEFAULT 'SAN_SANG' NOT NULL,
    gio_mo_cua          VARCHAR2(5),
    gio_dong_cua        VARCHAR2(5),
    ngay_tao            DATE DEFAULT SYSDATE,
    ngay_cap_nhat       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_san_bong_loai_san FOREIGN KEY (ma_loai_san) REFERENCES loai_san(ma_loai_san),
    CONSTRAINT chk_trang_thai_san 
        CHECK (trang_thai_san IN ('SAN_SANG', 'BAO_TRI', 'DANG_SU_DUNG', 'NGUNG_HOAT_DONG'))
);

-- =========================
-- 8. BANG GIA
-- =========================
CREATE TABLE bang_gia (
    ma_bang_gia         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_san              NUMBER NOT NULL,
    ten_bang_gia        VARCHAR2(100) NOT NULL,
    thu_trong_tuan      NUMBER,
    gio_bat_dau         VARCHAR2(5) NOT NULL,
    gio_ket_thuc        VARCHAR2(5) NOT NULL,
    gia_moi_gio         NUMBER(12,2) NOT NULL,
    ngay_ap_dung_tu     DATE NOT NULL,
    ngay_ap_dung_den    DATE,
    dang_ap_dung        NUMBER(1) DEFAULT 1 NOT NULL,
    ghi_chu             VARCHAR2(255),
    CONSTRAINT fk_bang_gia_san FOREIGN KEY (ma_san) REFERENCES san_bong(ma_san),
    CONSTRAINT chk_thu_trong_tuan 
        CHECK (thu_trong_tuan BETWEEN 1 AND 7 OR thu_trong_tuan IS NULL),
    CONSTRAINT chk_gia_moi_gio 
        CHECK (gia_moi_gio > 0),
    CONSTRAINT chk_dang_ap_dung 
        CHECK (dang_ap_dung IN (0,1))
);

-- =========================
-- 9. BANG UU DAI
-- =========================
CREATE TABLE uu_dai (
    ma_uu_dai               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_giam_gia             VARCHAR2(30) NOT NULL UNIQUE,
    ten_uu_dai              VARCHAR2(150) NOT NULL,
    mo_ta                   VARCHAR2(255),
    loai_giam_gia           VARCHAR2(20) NOT NULL,
    gia_tri_giam            NUMBER(12,2) NOT NULL,
    gia_tri_dat_toi_thieu   NUMBER(12,2) DEFAULT 0,
    ngay_bat_dau            DATE NOT NULL,
    ngay_ket_thuc           DATE NOT NULL,
    gio_bat_dau             VARCHAR2(5),
    gio_ket_thuc            VARCHAR2(5),
    dang_hoat_dong          NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT chk_loai_giam_gia 
        CHECK (loai_giam_gia IN ('PHAN_TRAM', 'SO_TIEN_CO_DINH')),
    CONSTRAINT chk_gia_tri_giam 
        CHECK (gia_tri_giam > 0),
    CONSTRAINT chk_dang_hoat_dong 
        CHECK (dang_hoat_dong IN (0,1))
);

CREATE TABLE uu_dai_san (
    ma_uu_dai           NUMBER NOT NULL,
    ma_san              NUMBER NOT NULL,
    PRIMARY KEY (ma_uu_dai, ma_san),
    CONSTRAINT fk_uu_dai_san_uu_dai FOREIGN KEY (ma_uu_dai) REFERENCES uu_dai(ma_uu_dai),
    CONSTRAINT fk_uu_dai_san_san FOREIGN KEY (ma_san) REFERENCES san_bong(ma_san)
);

CREATE TABLE uu_dai_khach_hang (
    ma_uu_dai           NUMBER NOT NULL,
    ma_khach_hang       NUMBER NOT NULL,
    PRIMARY KEY (ma_uu_dai, ma_khach_hang),
    CONSTRAINT fk_uu_dai_kh_uu_dai FOREIGN KEY (ma_uu_dai) REFERENCES uu_dai(ma_uu_dai),
    CONSTRAINT fk_uu_dai_kh_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang(ma_khach_hang)
);

-- =========================
-- 10. BANG DAT SAN
-- =========================
CREATE TABLE dat_san (
    ma_dat_san              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_dat_san_code         VARCHAR2(30) NOT NULL UNIQUE,
    ma_khach_hang           NUMBER NOT NULL,
    ma_san                  NUMBER NOT NULL,
    ma_nhan_vien_tao        NUMBER,
    ngay_dat                DATE NOT NULL,
    gio_bat_dau             VARCHAR2(5) NOT NULL,
    gio_ket_thuc            VARCHAR2(5) NOT NULL,
    trang_thai_dat_san      VARCHAR2(20) DEFAULT 'CHO_XU_LY' NOT NULL,
    ghi_chu                 VARCHAR2(500),
    tong_tien_goc           NUMBER(12,2) DEFAULT 0 NOT NULL,
    tien_giam               NUMBER(12,2) DEFAULT 0 NOT NULL,
    tong_tien_thanh_toan    NUMBER(12,2) DEFAULT 0 NOT NULL,
    ma_uu_dai               NUMBER,
    trang_thai_thanh_toan   VARCHAR2(20) DEFAULT 'CHUA_THANH_TOAN' NOT NULL,
    ngay_tao                DATE DEFAULT SYSDATE,
    ngay_cap_nhat           DATE DEFAULT SYSDATE,
    thoi_gian_check_in      DATE,
    CONSTRAINT fk_dat_san_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang(ma_khach_hang),
    CONSTRAINT fk_dat_san_san FOREIGN KEY (ma_san) REFERENCES san_bong(ma_san),
    CONSTRAINT fk_dat_san_nhan_vien FOREIGN KEY (ma_nhan_vien_tao) REFERENCES nhan_vien(ma_nhan_vien),
    CONSTRAINT fk_dat_san_uu_dai FOREIGN KEY (ma_uu_dai) REFERENCES uu_dai(ma_uu_dai),
    CONSTRAINT chk_trang_thai_dat_san 
        CHECK (trang_thai_dat_san IN ('CHO_XU_LY', 'DA_XAC_NHAN', 'DA_HUY', 'DA_CHECK_IN', 'DA_HOAN_THANH')),
    CONSTRAINT chk_trang_thai_tt_dat_san 
        CHECK (trang_thai_thanh_toan IN ('CHUA_THANH_TOAN', 'THANH_TOAN_MOT_PHAN', 'DA_THANH_TOAN', 'DA_HOAN_TIEN')),
    CONSTRAINT chk_tien_dat_san 
        CHECK (tong_tien_goc >= 0 AND tien_giam >= 0 AND tong_tien_thanh_toan >= 0)
);

-- =========================
-- 11. LICH SU TRANG THAI DAT SAN
-- =========================
CREATE TABLE lich_su_trang_thai_dat_san (
    ma_lich_su              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_dat_san              NUMBER NOT NULL,
    trang_thai_cu           VARCHAR2(20),
    trang_thai_moi          VARCHAR2(20) NOT NULL,
    ma_tai_khoan_thay_doi   NUMBER,
    thoi_gian_thay_doi      DATE DEFAULT SYSDATE,
    ghi_chu                 VARCHAR2(255),
    CONSTRAINT fk_ls_trang_thai_dat_san FOREIGN KEY (ma_dat_san) REFERENCES dat_san(ma_dat_san),
    CONSTRAINT fk_ls_tai_khoan FOREIGN KEY (ma_tai_khoan_thay_doi) REFERENCES tai_khoan(ma_tai_khoan)
);

-- =========================
-- 12. SAN YEU THICH
-- =========================
CREATE TABLE san_yeu_thich (
    ma_khach_hang       NUMBER NOT NULL,
    ma_san              NUMBER NOT NULL,
    ngay_tao            DATE DEFAULT SYSDATE,
    PRIMARY KEY (ma_khach_hang, ma_san),
    CONSTRAINT fk_san_yt_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang(ma_khach_hang),
    CONSTRAINT fk_san_yt_san FOREIGN KEY (ma_san) REFERENCES san_bong(ma_san)
);

-- =========================
-- 13. THANH TOAN
-- =========================
CREATE TABLE thanh_toan (
    ma_thanh_toan           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_dat_san              NUMBER NOT NULL UNIQUE,
    hinh_thuc_thanh_toan    VARCHAR2(20) NOT NULL,
    trang_thai_thanh_toan   VARCHAR2(20) NOT NULL,
    so_tien_thanh_toan      NUMBER(12,2) NOT NULL,
    thoi_gian_thanh_toan    DATE,
    ma_giao_dich            VARCHAR2(100),
    ma_nhan_vien_xac_nhan   NUMBER,
    ghi_chu                 VARCHAR2(255),
    CONSTRAINT fk_thanh_toan_dat_san FOREIGN KEY (ma_dat_san) REFERENCES dat_san(ma_dat_san),
    CONSTRAINT fk_thanh_toan_nhan_vien FOREIGN KEY (ma_nhan_vien_xac_nhan) REFERENCES nhan_vien(ma_nhan_vien),
    CONSTRAINT chk_hinh_thuc_thanh_toan 
        CHECK (hinh_thuc_thanh_toan IN ('TIEN_MAT', 'CHUYEN_KHOAN', 'THANH_TOAN_ONLINE', 'THANH_TOAN_TAI_SAN')),
    CONSTRAINT chk_trang_thai_thanh_toan 
        CHECK (trang_thai_thanh_toan IN ('CHO_XU_LY', 'THANH_CONG', 'THAT_BAI', 'CHO_XAC_NHAN')),
    CONSTRAINT chk_so_tien_thanh_toan 
        CHECK (so_tien_thanh_toan >= 0)
);

-- =========================
-- 14. HOA DON
-- =========================
CREATE TABLE hoa_don (
    ma_hoa_don              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_hoa_don_code         VARCHAR2(30) NOT NULL UNIQUE,
    ma_thanh_toan           NUMBER NOT NULL UNIQUE,
    ngay_xuat               DATE DEFAULT SYSDATE,
    tong_tien               NUMBER(12,2) NOT NULL,
    ghi_chu                 VARCHAR2(255),
    CONSTRAINT fk_hoa_don_thanh_toan FOREIGN KEY (ma_thanh_toan) REFERENCES thanh_toan(ma_thanh_toan),
    CONSTRAINT chk_tong_tien_hoa_don 
        CHECK (tong_tien >= 0)
);

-- =========================
-- 15. DU LIEU MAU
-- =========================
INSERT INTO vai_tro(ten_vai_tro, mo_ta) VALUES ('CHU_SAN', 'Chu san');
INSERT INTO vai_tro(ten_vai_tro, mo_ta) VALUES ('NHAN_VIEN', 'Nhan vien');
INSERT INTO vai_tro(ten_vai_tro, mo_ta) VALUES ('KHACH_HANG', 'Khach hang');

INSERT INTO loai_san(ten_loai_san, mo_ta) VALUES ('San 5', 'San bong da 5 nguoi');
INSERT INTO loai_san(ten_loai_san, mo_ta) VALUES ('San 7', 'San bong da 7 nguoi');
INSERT INTO loai_san(ten_loai_san, mo_ta) VALUES ('San 11', 'San bong da 11 nguoi');
INSERT INTO tai_khoan (
    ten_dang_nhap,
    mat_khau,
    ho_ten,
    email,
    so_dien_thoai,
    ma_vai_tro,
    trang_thai_tai_khoan
) VALUES (
             'admin',
             '123',
             'Chu san demo',
             'admin@gmail.com',
             '0909000001',
             1,
             'HOAT_DONG'
         );

COMMIT;
