db.name=FOOTBALL_PROJECT
db.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
db.username=FOOTBALL_APP
db.password=football123
mail.host=smtp.gmail.com
mail.port=587
mail.username=nguyenvantam8399@gmail.com
mail.password=ilpn gwjr supu qukg
mail.auth=true
mail.starttls=true
mail.from=nguyenvantam8399@gmail.com